### ISSUE TITLE
Need to add tests for API GET requests

### ISSUE THREAD

**Issue by Mcghee-Jake** [team-makeSmart/CST438#22]
Right now I am working on learning how to add tests to android since I have not had to do that before, so I am putting this off for now. If someone would like to take a stab at it please do otherwise I will try to take care of it later after more of the mobile components are complete.

The relevant code for this is

in config/routes.rb :
`get 'api/:username' => 'users#expenses_json'`

in app/controller :
  ```
def expenses_json
    user = User.find_by username: params[:username]
    @expenses = Expense.where(user_id: user.id)
  end
```

and the view file is 'expenses_json.json.jbuilder'

**Comment by mdoussias** [comment]
For this can we record this in pivotalTracker as a story so that it shows our progress?

**Comment by mdoussias** [comment]
I just added it as a story

**Comment by p12345vls** [comment]
Tested
